[versions]
accompanist = "0.36.0"
android-gradle = "8.8.0"
androidx-activity = "1.10.0"
composeUi = "1.7.8"
coroutines = "1.10.1"
kotlin = "2.1.10"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
# Not plugin plugins.
agp = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version = "7.0.2" }

androidx-core = { module = "androidx.core:core-ktx", version = "1.15.0" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.1" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }

composeUi-ui = { module = "androidx.compose.ui:ui", version.ref = "composeUi" }
composeUi-uiTestManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeUi" }
composeUi-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeUi" }
composeUi-uiTooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeUi" }
composeUi-material3 = { module = "androidx.compose.material3:material3", version = "1.3.1" }
composeUi-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }

material = { module = "com.google.android.material:material", version = "1.12.0" }

accompanist-systemUiController = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }
