apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.android'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'
apply plugin: 'com.diffplug.spotless'

android {
  namespace 'com.mattprecious.plates'
  compileSdk 34

  defaultConfig {
    applicationId "com.mattprecious.plates"

    minSdk 33
    targetSdk 35

    versionCode 2
    versionName "1.0"

    vectorDrawables {
      useSupportLibrary true
    }
  }

  buildTypes {
    debug {
      applicationIdSuffix '.debug'
    }

    release {
      minifyEnabled true
      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_11
    targetCompatibility JavaVersion.VERSION_11
  }

  buildFeatures {
    compose true
  }

  lintOptions {
    checkReleaseBuilds false // Full lint runs as part of 'build' task.
  }

  packagingOptions {
    exclude '/META-INF/{AL2.0,LGPL2.1}'
    exclude 'META-INF/*.kotlin_module'
    exclude 'META-INF/*.version'
  }

  testOptions {
    unitTests.returnDefaultValues = true
  }

  dependenciesInfo {
    includeInApk false
    includeInBundle false
  }
}

spotless {
  kotlin {
    target("src/**/*.kt")
    ktlint().editorConfigOverride([
      'ktlint_standard_filename': 'disabled',
    ])
  }
}

dependencies {
  implementation libs.accompanist.systemUiController
  implementation libs.androidx.activity
  implementation libs.androidx.core
  implementation libs.androidx.splashscreen
  implementation libs.composeUi.activity
  implementation libs.composeUi.ui
  implementation libs.composeUi.uiTooling.preview
  implementation libs.composeUi.material3
  implementation libs.coroutines.core
  implementation libs.material
  implementation libs.timber
  debugImplementation libs.composeUi.uiTooling
  debugImplementation libs.composeUi.uiTestManifest
}
